# Advanced Configuration for Negate CLI
batch_size: 4                           # Feature extraction batch size, zero to disable batching
cache_features: true                    # enable <chud> mode
vae_tiling: false                       # Enable VAE tiling
vae_slicing: false                      # Enable VAE scaling
patch_size: 768                         # Patch resolution
top_k: 1                                # Number of top patches to keep
use_onnx: false                          # True → ONNX, False → native XGBoost
dtype: bfloat16                         # vae dtype
default_vae: "Freepik/F-Lite-Texture"   # Model path

train:
  n_components: 0.95                      # Training PCA num components
  num_boost_round: 200                    # Boosted training rounds
  early_stopping_rounds: 10               # Early stop training
  colsample_bytree: 0.8
  eval_metric: ["logloss", "aucpr"]
  learning_rate: 0.1
  max_depth: 4
  objective:  "binary:logistic"
  subsample: 0.8
  scale_pos_weight: null
  seed: 0
